name: AcidicWeather
main: com.tenjava.entries.MOMOTHEREAL.t3.TenJava
version: '${project.version}'
commands:
  toggleacidic:
    description: Toggles the features of the plugin, in case the world needs a break from heavy duty.
    aliases: [ta, tacidic, toggleacid]
  hail:
    description: Starts a hail fall.
    aliases: [hailstorm]
  heatstroke:
    description: Starts a heatstroke.
    aliases: [heat]
  blizzard:
    description: Starts a blizzard.
  acidrain:
    description: Starts an acid rain.
    aliases: [acid]
  blackice:
    description: Starts a black ice storm.