name: AcidicWeather
main: com.tenjava.entries.MOMOTHEREAL.t3.TenJava
version: '${project.version}'
commands:
  toggleacidic:
    description: Toggles the features of the plugin, in case the world needs a break from heavy duty.
    aliases: [ta, tacidic, toggleacid]
